name: orthrus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 
  - numpy>=1.19.2
  - pandas>=1.1.3
  - scikit-learn>=0.23.2
  - sphinx=3.2.1
  - pip:
      - dash_core_components>=1.14.1
      - dill>=0.3.4
      - matplotlib>=3.3.36
      - numpy>=1.21.2
      - seaborn>=0.11.1
      - pandas>=1.1.3
      - ray>=1.4.1
      - dash_html_components>=1.1.1
      - plotly>=4.11.0
      - tqdm>=4.56.0
      - Flask>=1.1.2
      - dash>=1.18.1
      - harmonypy>=0.0.5
      - scikit_learn>=0.24.2
